spring.application.name=discografia
spring.mongodb.uri=mongodb+srv://jonathanastudilloleal_db_user:jona1988@eva-u3-express.9lxvbgg.mongodb.net/?appName=eva-u3-express
spring.mongodb.database=discografica-db
